build:
  options:
    dumpLineNumbers: true
    stripBanners: true
    syncImport: true
    strictImports: true
  src: ["src/static/less/app.less","src/common/**/*.less","src/app/**/*.less"]
  dest: "<%= cfg.buildDir %>/css/app.css"
